# Pandas 
## veri bilimi için vb kullanılır. Panel Data kısaltılmısı
## numpy genişletilmiş halidir
## farklı veri tipleri ile calısır
## Veri manipülasyonu ve veri analizi için yazılmıs acık kaynak kodlu bir Python kütüphanesidir
## Ekonometrik ve finansal çalışmalar için doğmuştur
## 2008 yılında yapılıyor. Mevcut Python yetersiz germesi sonucu Pandas kütüphanesini oluşturuyor.
## Finans ihtiyacından doğuyor. Zaman serileri demek istatisitk demek, veri ile iç içe olmak demek.
## Dataframe  üzerinde calısmamızı saglar. 
## Pandas bir çok veri tipini okuma ve yazma imkanı sağlar.

# Pandas serisi oluşturmak

In [5]:
import pandas as pd

In [9]:
seri = pd.Series([1,2,3,4,5])
# ilk sutun index ikinci sutun value. numpydan farkı budur.
seri

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
type(seri)

pandas.core.series.Series

In [15]:
seri.axes # 0 dan baslayıp 5 e kadar 1 er  gitmiş

[RangeIndex(start=0, stop=5, step=1)]

In [17]:
seri.dtype

dtype('int64')

In [19]:
seri.size

5

In [23]:
seri.ndim # boyut

1

In [27]:
seri.values # value erisebiliriz

array([1, 2, 3, 4, 5], dtype=int64)

In [29]:
seri.values[1]

2

In [31]:
seri.head() # seri ilk 5 degerini getirir.

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [33]:
seri.head(3) 3 ilk 3 degeri getirir

0    1
1    2
2    3
dtype: int64

In [37]:
seri.tail(3) # elemanlara sondan bakmak

2    3
3    4
4    5
dtype: int64

In [39]:
# index isimlendirmesi
pd.Series([99,22,33,55,94])

0    99
1    22
2    33
3    55
4    94
dtype: int64

In [41]:
pd.Series([99,22,33,55,94],index =[1,3,5,7,9])

1    99
3    22
5    33
7    55
9    94
dtype: int64

In [45]:
# string degerle isimlendirme
seri =pd.Series([99,22,33,55,94],index =["a","b","c","d","e"])

In [47]:
seri

a    99
b    22
c    33
d    55
e    94
dtype: int64

In [49]:
seri["a"]

99

In [51]:
seri["a":"c"] # slice işlemi

a    99
b    22
c    33
dtype: int64

In [53]:
# sozluk uzerinden liste olusturmak
sozluk = pd.Series({"reg":10,"log":11,"char":12})

In [55]:
sozluk

reg     10
log     11
char    12
dtype: int64

In [59]:
sozluk = {"reg":10,"log":11,"char":12}
sozluk_seri = pd.Series(sozluk)

In [67]:
sozluk_seri

reg     10
log     11
char    12
dtype: int64

In [71]:
# iki seriyi birleştirme ve seri olusturma
pd.concat([sozluk_seri,sozluk_seri])

reg     10
log     11
char    12
reg     10
log     11
char    12
dtype: int64

In [75]:
# Serilerde Eleman işlemleri
import numpy as np
import pandas as pd
a = np.array([1,2,33,44,55,75])
seri = pd.Series(a)
seri

0     1
1     2
2    33
3    44
4    55
5    75
dtype: int32

In [77]:
seri.values

array([ 1,  2, 33, 44, 55, 75])

In [79]:
seri[0]

1

In [89]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [91]:
seri[0:3].values

array([ 1,  2, 33])

In [95]:
seri = pd.Series([11,22,33,44],index=["reg","log","cart","rf"])
seri

reg     11
log     22
cart    33
rf      44
dtype: int64

In [101]:
seri.index # sadece indexlere erisiriz

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

In [103]:
seri.keys

<bound method Series.keys of reg     11
log     22
cart    33
rf      44
dtype: int64>

In [99]:
seri.values

array([11, 22, 33, 44], dtype=int64)

In [107]:
list(seri.items()) # key ve value formunda getiririz

[('reg', 11), ('log', 22), ('cart', 33), ('rf', 44)]

In [109]:
seri.values

array([11, 22, 33, 44], dtype=int64)

In [113]:
# eleman sorgulama
"reg" in seri # reg seri icinde mi

True

In [115]:
"a" in seri

False

In [117]:
seri["reg"]

11

In [121]:
# fancy eleman
seri[["rf","reg"]]

rf     44
reg    11
dtype: int64

In [123]:
seri["reg"]

11

In [125]:
seri["reg":"log"]

reg    11
log    22
dtype: int64