# Pandas DataFrame olusturma yapısal veri tipi excel veri tipine benzer

In [167]:
import pandas as pd

In [169]:
l = [1,2,3,4,66,55]

In [171]:
l

[1, 2, 3, 4, 66, 55]

In [173]:
pd.DataFrame(l, columns = ["degisken_ismi"])

,degisken_ismi
0,1
1,2
2,3
3,4
4,66
5,55


In [175]:
import numpy as np

In [177]:
m = np.arange(1,10).reshape((3,3))

In [179]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [180]:
pd.DataFrame(m,columns = ["var1","var2","var3"])

,var1,var2,var3
0,1,2,3
1,4,5,6
2,7,8,9


In [183]:
# df isimlendirme

In [185]:
df = pd.DataFrame(m,columns=["var1","var2","var3"])
df

,var1,var2,var3
0,1,2,3
1,4,5,6
2,7,8,9


In [186]:
df.head(1)

,var1,var2,var3
0,1,2,3


In [189]:
df.columns  # desişkenlerin iismleri getiriyor

Index(['var1', 'var2', 'var3'], dtype='object')

In [190]:
df.columns = ("deg1","deg2","deg3")

In [193]:
df.columns

Index(['deg1', 'deg2', 'deg3'], dtype='object')

In [195]:
type(df)

pandas.core.frame.DataFrame

In [197]:
df.axes # axes satır ve sutun bilgilerini veriyor

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [198]:
df.shape # boyut bilgisi

(3, 3)

In [200]:
df.ndim # satır ve sutundan olusutr 2 boyut gelir

2

In [202]:
df.size # eleman sayısı

9

In [203]:
df.values # elemanlara erisir

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [204]:
type(df.values)

numpy.ndarray

In [205]:
df.head() # bastan degerleri verir

,deg1,deg2,deg3
0,1,2,3
1,4,5,6
2,7,8,9


In [206]:
df.tail(1) #sondan degerleri verir

,deg1,deg2,deg3
2,7,8,9


In [208]:
a = np.array([11,22,33,44,55])
a

array([11, 22, 33, 44, 55])

In [209]:
pd.DataFrame(a,columns =["deg1"])

,deg1
0,11
1,22
2,33
3,44
4,55


In [210]:
# Eleman işlemleri
import pandas as pd
import numpy as np
s1 = np.random.randint(10,size=5)
s2 = np.random.randint(10,size = 5)
s3 = np.random.randint(10,size=5)

In [212]:
s1

array([5, 6, 5, 1, 8])

In [213]:
s2

array([5, 8, 5, 6, 3])

In [214]:
s3

array([3, 4, 1, 0, 2])

In [219]:
sozluk = {"var1":s1,"var2":s2,"var3":s3}
sozluk

{'var1': array([5, 6, 5, 1, 8]),
 'var2': array([5, 8, 5, 6, 3]),
 'var3': array([3, 4, 1, 0, 2])}

In [220]:
df = pd.DataFrame(sozluk)
df

,var1,var2,var3
0,5,5,3
1,6,8,4
2,5,5,1
3,1,6,0
4,8,3,2


In [221]:
df[0:2]

,var1,var2,var3
0,5,5,3
1,6,8,4


In [222]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [223]:
df.index = ["a","b","c","d","e"]

In [225]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [226]:
df["c":"e"]

,var1,var2,var3
c,5,5,1
d,1,6,0
e,8,3,2


In [227]:
# silme
df.drop("a",axis=0)

,var1,var2,var3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2


In [230]:
df # ana veri siitnde a silinmedi

,var1,var2,var3
a,5,5,3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2


In [231]:
df.drop("a",axis=0, inplace=True) # ilk satır kalıcı olarak ucar. df uzerindeki degisikligi kalıcı olarak yapar
# axis = 0 satır 1 sutun verir

In [232]:
df

,var1,var2,var3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2


In [233]:
# fancy index
l = ["c","e"]

In [234]:
df.drop(l,axis=0)

,var1,var2,var3
b,6,8,4
d,1,6,0


In [237]:
df

,var1,var2,var3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2


In [239]:
# degiskenler için
"var1" in df

True

In [240]:
l = ["var1","var4","var2"]

In [241]:
for i in l:
    print(i in df)

True
False
True


In [242]:
df

,var1,var2,var3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2


In [243]:
df["var1"]

b    6
c    5
d    1
e    8
Name: var1, dtype: int32

In [244]:
df["var4"] = df["var1"]/df["var2"]

In [245]:
df

,var1,var2,var3,var4
b,6,8,4,0.750000
c,5,5,1,1.000000
d,1,6,0,0.166667
e,8,3,2,2.666667


In [246]:
# degisken silme
df.drop("var4",axis=1)

,var1,var2,var3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2


In [247]:
df

,var1,var2,var3,var4
b,6,8,4,0.750000
c,5,5,1,1.000000
d,1,6,0,0.166667
e,8,3,2,2.666667


In [248]:
df.drop("var4",axis=1,inplace=True) # inplace kalıcı olarak df uzerinde degiisklik yapar

In [298]:
df

,var1,var2,var3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2


In [300]:
# fancy ile silme islemi
l =["var1","var2"]

In [302]:
df.drop(l,axis=1)

,var3
b,4
c,1
d,0
e,2


In [304]:
df

,var1,var2,var3
b,6,8,4
c,5,5,1
d,1,6,0
e,8,3,2
