In [16]:

print("Hello world")


Hello world


Merhaba 
harhangi bir bilgide yazılabilir

_merhaba_
**Kalın** yazı yazabiliriz 




**Numpy** --> Numerical Python
Bilimsel hesaplamalar icin kullanılır
Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar
vektörer hesaplamalar yapılmasını imkan saglar


sol ust taraftaki + sembolu ıle yenı hucre ekleyebiliriz.
Eger hucrenın dısına cıkıp b ile altına  a ile de hucrenın ustune yenı hucre eklemıs oluruz





hucrenin dısında x ile hücreyi kesme ve v ile de hücreyi yapıstırma yaparız. Aynı şekilde c ile de kopyalama ve v ile de yapıstırma yapmıs oluruz.

Hücre icinde kopyalama yapıstırma kesme yapmak ctrl x c ve v 
hücreleri kesme kopyalama ve yapıstırma istiyorsak da sadece x,c,v tuslarını kullanırız
hucreleri silmek icin iki defa d basmalıyız d+d


# Neden NumPy
 (#) ile en buyuk baslık olur

## Alt baslık
(##) ile alt baslık

In [51]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]
a
b
# sadece en son ifadeyi yazdırır

[2, 3, 4, 5, 6]

In [45]:
a

[1, 2, 3, 4, 5]

In [75]:
b # hucrelerde parca parca kodları yazdırmamıs saglar
type(b)

numpy.ndarray

In [55]:
# a ve b carpmak ıstersek fonksiyonel programlamada for dongusu ıle yapmıstık

ab = []

for i in range(len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20, 30]

matris vb yuksek boyutlu ifadeleri carpmak icin bu skeılde for donguus ile karısık ifadeleri kullanmamız veirmli olmaz


In [58]:
import numpy as np

In [60]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [64]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [67]:
import numpy as np

In [69]:
a = np.array([1,2,3,4,5])

In [71]:
type(a)

numpy.ndarray

In [77]:
b = np.array([3.14,4,2,3,13])

In [79]:
b
type(b)

numpy.ndarray

In [85]:
b = np.array([3.14,4,2,3,13], dtype="int") #int cevirir

In [91]:
b


array([ 3,  4,  2,  3, 13])

# sıfırdan array olusturma

In [96]:
np.zeros(10,dtype="int")


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [102]:
# eger belirli sayıdan array olusturma ıcın

np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [104]:
# dogrusal dizi
# iki deger arasında artan deger

np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [110]:
# iki deger arasında belirli sayıda deger

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [118]:
# ortalama 10 standart sapma 4 olacak sekılde dagılım olusturabiliriz

np.random.normal(10,4,(3,4))


array([[11.48614221,  9.90444008, 10.11953049, 12.97722623],
       [ 9.88607097, 11.71353854, 15.3891415 ,  8.48585577],
       [10.79503572,  7.38401753,  8.80252889,  9.4336601 ]])

In [124]:
np.random.randint(0,10,(3,4))

array([[8, 2, 9, 6],
       [7, 6, 7, 0],
       [6, 2, 7, 0]])

# Özellikleri
* **ndim:** _boyut sayısı_
* **shape:** boyut bilgisi
* _**size:**_ toplam eleman sayısı
* _**dtype:**_ array veri tipi

In [134]:
import numpy as np

In [136]:
np.random.randint(10,size=10)

array([5, 4, 5, 6, 6, 1, 3, 2, 6, 3])

In [138]:
a = np.random.randint(10,size=10)

In [140]:
a.ndim # boyut sayısı

1

In [142]:
a.shape # boyut bılgısı 10 row var demek

(10,)

In [148]:
a.size # toplam eleman sayısı

10

In [154]:
a.dtype # array veri tipi

dtype('int32')

In [158]:
b = np.random.randint(10,size=(3,5))

In [160]:
b

array([[0, 8, 4, 2, 0],
       [9, 5, 6, 2, 7],
       [2, 3, 2, 5, 2]])

In [162]:
b.ndim

2

In [164]:
b.shape

(3, 5)

In [166]:
b.size

15

In [168]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (reshaping)

In [171]:
import numpy as np

In [193]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
a = np.arange(1,10)

In [203]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [205]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
a.ndim # vektor tek boyut 2 boyut matrix

1

In [221]:
b = a.reshape((1,9))

In [223]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [225]:
b.ndim

2

In [227]:
b.size

9

In [219]:
a.ndim

1

# Array Birlestirme (concatenation)

In [234]:
import numpy as np

In [236]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [240]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [247]:
z = np.array([7,8,9])

In [249]:
z

array([7, 8, 9])

In [251]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [253]:
# iki boyut
a = np.array([[1,2,3],
             [4,5,6]])

In [259]:
np.concatenate([a,a], axis=0) # satır baz birlestirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [261]:
# sütün baz birleştirme
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [2]:
import numpy as np

In [14]:
x = np.array([1,2,3,99,99,3,2,1])

In [16]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [20]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [22]:
a,b,c =np.split(x, [3,5])

In [24]:
a

array([1, 2, 3])

In [26]:
b

array([99, 99])

In [28]:
c

array([3, 2, 1])

# iki boyutlu ayırma

In [31]:
m = np.arange(16).reshape(4,4)

In [33]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
d = np.vsplit(m,[2]) # vertical split

In [43]:
alt, ust =d

In [45]:
alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
ust

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.hsplit(m,[2]) # horizantal split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
sol, sag = np.hsplit(m,[2]) # horizantal split

In [65]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [67]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

# Array Sıralama (Sorting)

In [84]:
import numpy as np

In [86]:
v = np.array([2,1,4,3,5])

In [88]:
v

array([2, 1, 4, 3, 5])

In [90]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [92]:
v

array([2, 1, 4, 3, 5])

In [94]:
v.sort()

In [96]:
v

array([1, 2, 3, 4, 5])

# iki boyutlu array sıralama

In [132]:
import numpy as np

In [134]:
# ortalaması 20 std sapmas 5 olacak sekılde 3 3 luk matrix
m = np.random.normal(20,5,(3,3))

In [136]:
m

array([[22.11729688, 17.33189908, 17.99844725],
       [12.40480939, 17.98739529, 25.69891594],
       [23.9450175 , 24.10239261, 21.22291733]])

In [138]:
#satırları sıralayalım
np.sort(m,axis=1)
# her bir satırı kucukten buyuge sıraladı

array([[17.33189908, 17.99844725, 22.11729688],
       [12.40480939, 17.98739529, 25.69891594],
       [21.22291733, 23.9450175 , 24.10239261]])

In [141]:
np.sort(m,axis=0)
# column sıralar

array([[12.40480939, 17.33189908, 17.99844725],
       [22.11729688, 17.98739529, 21.22291733],
       [23.9450175 , 24.10239261, 25.69891594]])

# Index ile Elemanlara Erişmek

In [152]:
import numpy as np
a = np.random.randint(10,size=10)

In [154]:
a

array([2, 8, 3, 3, 5, 2, 6, 3, 9, 5])

In [156]:
a[0] # ilk eleman

2

In [160]:
a[-1] # tersten son eleman

5

In [162]:
a[0] = 100

In [164]:
a

array([100,   8,   3,   3,   5,   2,   6,   3,   9,   5])

# iki boyutlu index ile elemana erisme

In [219]:
import numpy as np

In [221]:
m = np.random.randint(10,size=(3,5))

In [223]:
m

array([[4, 6, 7, 4, 2],
       [8, 6, 1, 3, 9],
       [3, 1, 3, 5, 7]])

In [225]:
m[0][0]

4

In [227]:
m[1,1]

6

In [229]:
m[2,4]

7

In [236]:
m[2,4] = 15.5

In [238]:
m

array([[ 4,  6,  7,  4,  2],
       [ 8,  6,  1,  3,  9],
       [ 3,  1,  3,  5, 15]])

# Slicing ile Elemanlara Erişmek
## Alt kümeye erişmek

In [241]:
import numpy as np

In [243]:
a = np.arange(20,30)

In [245]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [247]:
a[0:3]

array([20, 21, 22])

In [249]:
a[:3]

array([20, 21, 22])

In [251]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [253]:
a[1::2] # ikiser atlayarak sayar

array([21, 23, 25, 27, 29])

In [255]:
a[0::2] # ikiser atlayarak sayar

array([20, 22, 24, 26, 28])

In [263]:
a[::3] # ücer atlayarak sayar

array([20, 23, 26, 29])

# iki boyutlu slice islemleri

In [273]:
import numpy as np

In [279]:
m = np.random.randint(10,size=(5,5))

In [281]:
m

array([[0, 7, 7, 3, 8],
       [4, 1, 0, 1, 5],
       [9, 4, 6, 6, 8],
       [2, 5, 7, 8, 7],
       [2, 4, 7, 1, 0]])

In [287]:
m[:,0] # butun satırlar sec ve 0. sutun sec

array([0, 4, 9, 2, 2])

In [289]:
m[:,3] # butun satırlar sec ve 0. sutun sec

array([3, 1, 6, 8, 1])

In [293]:
m

array([[0, 7, 7, 3, 8],
       [4, 1, 0, 1, 5],
       [9, 4, 6, 6, 8],
       [2, 5, 7, 8, 7],
       [2, 4, 7, 1, 0]])

In [295]:
m[0,:]

array([0, 7, 7, 3, 8])

In [297]:
m[0] # ilk satır ceker

array([0, 7, 7, 3, 8])

In [299]:
m[1,:] # 1 satır tum sutunlar

array([4, 1, 0, 1, 5])

In [303]:
# hem satır hem sutun
m

array([[0, 7, 7, 3, 8],
       [4, 1, 0, 1, 5],
       [9, 4, 6, 6, 8],
       [2, 5, 7, 8, 7],
       [2, 4, 7, 1, 0]])

In [307]:
m[0:2,0:3] # 0-2 satır 0-3 sutun

array([[0, 7, 7],
       [4, 1, 0]])

In [324]:
m

array([[0, 7, 7, 3, 8],
       [4, 1, 0, 1, 5],
       [9, 4, 6, 6, 8],
       [2, 5, 7, 8, 7],
       [2, 4, 7, 1, 0]])

In [326]:
m[::2,:2] # tum satırlar 2 ser al 0-2 sutun

array([[0, 7],
       [9, 4],
       [2, 4]])

In [320]:
m[:,:2] # tum satırlar 0-2 sutun

array([[0, 7],
       [4, 1],
       [9, 4],
       [2, 5],
       [2, 4]])

In [328]:
m

array([[0, 7, 7, 3, 8],
       [4, 1, 0, 1, 5],
       [9, 4, 6, 6, 8],
       [2, 5, 7, 8, 7],
       [2, 4, 7, 1, 0]])

In [330]:
m[1:3,0:2]

array([[4, 1],
       [9, 4]])

# Alt kume uzerinde işlem yapmak

In [333]:
import numpy as np

In [335]:
a = np.random.randint(10,size=(5,5))

In [337]:
a

array([[1, 7, 8, 7, 7],
       [5, 3, 7, 0, 1],
       [2, 4, 7, 9, 6],
       [7, 8, 9, 5, 7],
       [2, 9, 5, 7, 2]])

In [341]:
alt_a = a[0:3,0:2]
alt_a

array([[1, 7],
       [5, 3],
       [2, 4]])

In [343]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [345]:
alt_a

array([[99999,     7],
       [    5,   888],
       [    2,     4]])

In [349]:
a # yapılan degisiklikler a da da oldu. bu duurmu bazen istemeyiz

array([[99999,     7,     8,     7,     7],
       [    5,   888,     7,     0,     1],
       [    2,     4,     7,     9,     6],
       [    7,     8,     9,     5,     7],
       [    2,     9,     5,     7,     2]])

In [353]:
#bunun icin copy isimli metod kullanacagız
import numpy as np
m = np.random.randint(10,size=(5,5))
m

array([[3, 6, 9, 7, 5],
       [8, 6, 9, 7, 3],
       [3, 0, 9, 4, 1],
       [5, 6, 5, 1, 1],
       [3, 7, 5, 9, 2]])

In [357]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[3, 6],
       [8, 6],
       [3, 0]])

In [359]:
alt_b[0,0] = 9999
alt_b[1,1] = 8888

In [362]:
alt_b

array([[9999,    6],
       [   8, 8888],
       [   3,    0]])

In [366]:
m # copy ile olustuurlan arrayın yapısında degisiklik gozlenmedi

array([[3, 6, 9, 7, 5],
       [8, 6, 9, 7, 3],
       [3, 0, 9, 4, 1],
       [5, 6, 5, 1, 1],
       [3, 7, 5, 9, 2]])