In [16]:

print("Hello world")


Hello world


Merhaba 
harhangi bir bilgide yazılabilir

_merhaba_
**Kalın** yazı yazabiliriz 




**Numpy** --> Numerical Python
Bilimsel hesaplamalar icin kullanılır
Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar
vektörer hesaplamalar yapılmasını imkan saglar


sol ust taraftaki + sembolu ıle yenı hucre ekleyebiliriz.
Eger hucrenın dısına cıkıp b ile altına  a ile de hucrenın ustune yenı hucre eklemıs oluruz





hucrenin dısında x ile hücreyi kesme ve v ile de hücreyi yapıstırma yaparız. Aynı şekilde c ile de kopyalama ve v ile de yapıstırma yapmıs oluruz.

Hücre icinde kopyalama yapıstırma kesme yapmak ctrl x c ve v 
hücreleri kesme kopyalama ve yapıstırma istiyorsak da sadece x,c,v tuslarını kullanırız
hucreleri silmek icin iki defa d basmalıyız d+d


# Neden NumPy
 (#) ile en buyuk baslık olur

## Alt baslık
(##) ile alt baslık

In [51]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]
a
b
# sadece en son ifadeyi yazdırır

[2, 3, 4, 5, 6]

In [45]:
a

[1, 2, 3, 4, 5]

In [75]:
b # hucrelerde parca parca kodları yazdırmamıs saglar
type(b)

numpy.ndarray

In [55]:
# a ve b carpmak ıstersek fonksiyonel programlamada for dongusu ıle yapmıstık

ab = []

for i in range(len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20, 30]

matris vb yuksek boyutlu ifadeleri carpmak icin bu skeılde for donguus ile karısık ifadeleri kullanmamız veirmli olmaz


In [58]:
import numpy as np

In [60]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [64]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [67]:
import numpy as np

In [69]:
a = np.array([1,2,3,4,5])

In [71]:
type(a)

numpy.ndarray

In [77]:
b = np.array([3.14,4,2,3,13])

In [79]:
b
type(b)

numpy.ndarray

In [85]:
b = np.array([3.14,4,2,3,13], dtype="int") #int cevirir

In [91]:
b


array([ 3,  4,  2,  3, 13])

# sıfırdan array olusturma

In [96]:
np.zeros(10,dtype="int")


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [102]:
# eger belirli sayıdan array olusturma ıcın

np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [104]:
# dogrusal dizi
# iki deger arasında artan deger

np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [110]:
# iki deger arasında belirli sayıda deger

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [118]:
# ortalama 10 standart sapma 4 olacak sekılde dagılım olusturabiliriz

np.random.normal(10,4,(3,4))


array([[11.48614221,  9.90444008, 10.11953049, 12.97722623],
       [ 9.88607097, 11.71353854, 15.3891415 ,  8.48585577],
       [10.79503572,  7.38401753,  8.80252889,  9.4336601 ]])

In [124]:
np.random.randint(0,10,(3,4))

array([[8, 2, 9, 6],
       [7, 6, 7, 0],
       [6, 2, 7, 0]])

# Özellikleri
* **ndim:** _boyut sayısı_
* **shape:** boyut bilgisi
* _**size:**_ toplam eleman sayısı
* _**dtype:**_ array veri tipi

In [134]:
import numpy as np

In [136]:
np.random.randint(10,size=10)

array([5, 4, 5, 6, 6, 1, 3, 2, 6, 3])

In [138]:
a = np.random.randint(10,size=10)

In [140]:
a.ndim # boyut sayısı

1

In [142]:
a.shape # boyut bılgısı 10 row var demek

(10,)

In [148]:
a.size # toplam eleman sayısı

10

In [154]:
a.dtype # array veri tipi

dtype('int32')

In [158]:
b = np.random.randint(10,size=(3,5))

In [160]:
b

array([[0, 8, 4, 2, 0],
       [9, 5, 6, 2, 7],
       [2, 3, 2, 5, 2]])

In [162]:
b.ndim

2

In [164]:
b.shape

(3, 5)

In [166]:
b.size

15

In [168]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (reshaping)

In [171]:
import numpy as np

In [193]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
a = np.arange(1,10)

In [203]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [205]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
a.ndim # vektor tek boyut 2 boyut matrix

1

In [221]:
b = a.reshape((1,9))

In [223]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [225]:
b.ndim

2

In [227]:
b.size

9

In [219]:
a.ndim

1

# Array Birlestirme (concatenation)

In [234]:
import numpy as np

In [236]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [240]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [247]:
z = np.array([7,8,9])

In [249]:
z

array([7, 8, 9])

In [251]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [253]:
# iki boyut
a = np.array([[1,2,3],
             [4,5,6]])

In [259]:
np.concatenate([a,a], axis=0) # satır baz birlestirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [261]:
# sütün baz birleştirme
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])